site_name: ESPHome Developer Documentation
site_author: ESPHome
site_url: https://developers.esphome.io/

repo_url: https://github.com/esphome/developers.esphome.io/
repo_name: developers.esphome.io
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky

    - search.suggest
    - search.highlight

    # - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - toc.follow
  logo: images/logo.svg

  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - blog
  - search
  - mermaid2

hooks:
  - hooks/copyright.py
  - hooks/comments-toc.py

nav:
  - Home: index.md
  - Contributing:
    - Development environment: contributing/development-environment.md
    - Submitting your work: contributing/submitting-your-work.md
    - Contributing:
      - Code: contributing/code.md
      - Documentation: contributing/docs.md
  - Architecture:
    - Overview: architecture/overview.md
    - Core: architecture/core.md
    - Components:
      - Overview: architecture/components/index.md
      - Common hardware interfaces:
        - GPIO: architecture/components/gpio.md
        - I2C: architecture/components/i2c.md
        - SPI: architecture/components/spi.md
        - Serial (UART): architecture/components/uart.md
      - Automations: architecture/components/automations.md
    - API:
      - Overview: architecture/api/index.md
      - Protocol Details: architecture/api/protocol_details.md
    - Logging Best Practices: architecture/logging.md
  - Blog: blog/index.md
