site_name: ESPHome Developers
site_author: ESPHome
site_url: https://developers.esphome.io
site_description: This site is meanly for people that want to extend the functionality of ESPHome.
copyright: <strong>ESPHome</strong> is an open source project by <a href="https://https://www.nabucasa.com/">Nabu Casa</a>

repo_url: https://github.com/esphome/developers.esphome.io
repo_name: esphome/developers.esphome.io
edit_uri: edit/main/docs/

watch:
  - ext_theme

theme:
  name: material
  locale: en
  custom_dir: ext_theme
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:

    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - announce.dismiss
    - header.autohide
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      title: On this page
  - admonition
  - def_list
  - abbr
  - attr_list
  - tables
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true




plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - redirects:
      redirect_maps: {}
