site_name: ESPHome Developer Documentation
site_author: ESPHome
site_url: https://developers.esphome.io/

repo_url: https://github.com/esphome/developers.esphome.io/
repo_name: developers.esphome.io
edit_uri: edit/main/docs/

header_title: Developers

theme:
  name: material
  features:
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky

    - search.suggest
    - search.highlight

    # - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - toc.follow

  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - blog
  - privacy
  - search

hooks:
  - hooks/copyright.py

nav:
  - Home: index.md
  - Contributing:
    - Getting started: contributing/getting-started.md
    - Development environment: contributing/development-environment.md
    - Submitting your work: contributing/submitting-your-work.md
    - Contributing:
      - Code: contributing/code.md
      - Documentation: contributing/docs.md
      - Important notes: contributing/code-notes.md
  - Architecture:
    - Overview: architecture/overview.md
    - Core: architecture/core.md
    - Components:
      - Overview: architecture/components/index.md
      - Alarm control panel: architecture/components/alarm_control_panel.md
      - Binary sensor: architecture/components/binary_sensor.md
      - Button: architecture/components/button.md
      - Climate: architecture/components/climate.md
      - Cover: architecture/components/cover.md
      - Display: architecture/components/display.md
      - Event: architecture/components/event.md
      - Fan: architecture/components/fan.md
      - Light: architecture/components/light.md
      - Lock: architecture/components/lock.md
      - Media player: architecture/components/media_player.md
      - Number: architecture/components/number.md
      - Output: architecture/components/output.md
      - Select: architecture/components/select.md
      - Sensor: architecture/components/sensor.md
      - Speaker: architecture/components/speaker.md
      - Switch: architecture/components/switch.md
      - Text: architecture/components/text.md
      - Text sensor: architecture/components/text_sensor.md
      - Time: architecture/components/time.md
      - Touchscreen: architecture/components/touchscreen.md
      - Valve: architecture/components/valve.md
    - API: architecture/api
  - Blog: blog/index.md
