authors:
  jesserockz:
    name: Jesse Hills
    description: ESPHome Maintainer
    avatar: https://github.com/jesserockz.png
    url: https://github.com/jesserockz
  kbx81:
    name: Keith Burzinski
    description: ESPHome Maintainer
    avatar: https://github.com/kbx81.png
    url: https://github.com/kbx81
